language: generic
sudo: required
services:
    - docker

before_install: 
    - docker build -t alaindiez/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alaindiez/docker-react npm run test