language: generic
sudo: required
services:
    - docker

before_install: 
    - docker build -t alaindiez/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alaindiez/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-3-115697118774"
    bucket_path: "docker"
    on: 
        branch: main
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"