sudo: required
services:
    - docker

before_install: 
    - docker build -t alaindiez/docker-react -f Dockerfile.dev .

    script:
        - docker run alaindiez/docker-react npm run test -- --coverage